DROP DATABASE IF EXISTS burger_db;

CREATE DATABASE burgers_db;

USE burger_db;
CREATE TABLE burgers (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    burger_name VARCHAR (255) NOT NULL,
    devoured BOOL NOT NULL DEFAULT 0
);